version: '2'

services:

# cache redis server
 redis:
  container_name: redis
  image: redis
  restart: always

 rester-php:
  container_name: rester-php
  image: rester/rester-docker
  restart: always
  links:
    - redis:cache.rester.io
  volumes:
   - //Github/RESTer/rester-php/default.conf:/etc/nginx/sites-available/default.conf:ro
   - //Github/RESTer/rester-php/src:/var/www/html
   - //Github/RESTer/rester-php/cfg:/var/www/cfg:ro
  ports:
   - '80:80'
   - '443:443'
