version: '2'

services:

# cache redis server
 redis:
  container_name: redis
  image: redis
  restart: always

  # sample database
 db:
  container_name: db
  image: mariadb
  restart: always
  ports:
    - 3306:3306
  volumes:
    - ./example_db.sql:/docker-entrypoint-initdb.d/dump.sql
  environment:
   MYSQL_RANDOM_ROOT_PASSWORD: "${MYSQL_RANDOM_ROOT_PASSWORD}"
   MYSQL_DATABASE: "${MYSQL_DATABASE}"
   MYSQL_USER: "${MYSQL_USER}"
   MYSQL_PASSWORD: "${MYSQL_PASSWORD}"

 rester-php:
  container_name: rester-php
  image: kevinpark/rester-php
  restart: always
  links:
    - redis:cache.rester.kr
    - db:db.rester.kr
  volumes:
  - ./files:/var/www/html/rester/files
  - ./src/rester/lib:/var/www/html/rester/lib
  - ./src/modules:/var/www/html/modules
  - ./cfg:/var/www/cfg:ro
  ports:
  - '80:80'
