version: '2'

services:

# cache redis server
 redis:
  container_name: redis
  image: redis
  restart: always

 rester-php:
  container_name: rester-php
  image: rester/rester-docker
  restart: always
  links:
    - redis:cache.rester.io
  volumes:
   - ./default.conf:/etc/nginx/sites-available/default.conf:ro
   - ./default-ssl.conf:/etc/nginx/sites-available/default-ssl.conf:ro
   - ./cfg:/var/www/cfg:ro
   - ./lib:/var/www/lib
   - ./exten_lib:/var/www/exten_lib
   - ./src:/var/www/src
  ports:
   - '80:80'
   - '443:443'
